List<Map<String, dynamic>> cropData = [
  {
    "Name":"Chilli",
    "Category":"Vegetables",
    "Sowing":"i. Prior to sowing, assess if the soil is suitable for chilli cultivation, favoring black soil or soil with a pH between 5.5 and 8.5 and prepare soil by well draining.\nii. Select the appropriate chilli variety for planting before sowing.\niii. Sow the chilli seeds between the end of June and the first two weeks of July for optimal growth conditions.",
    "Germination and Transplantation":"It takes 5-10 days for the seeds to sprout. After 40-45 days, move the seedlings to a new spot. Once transplanted, trim away any excess growth and weeds.",
    "Ideal Growth Conditions":"Keep the soil temperature in the range of 24-29°C and ensure regular watering without saturating the soil ",
    "Fertilisation":"Apply balanced fertilizer every month, use pesticides when there are many chili pests, and adjust fertilizer based on soil fertility levels.",
    "Harvesting":"Harvest usually happens in early January. With good irrigation, chili plants can yield 2-3 times. Make sure to cut carefully with clean tools and store the harvest in a dry place.",
  },
  {
    "Name":"Tomato",
    "Category":"Vegetables",
    "Sowing":"i.Prior to sowing, assess if the soil is suitable for Tomato cultivation, favoring sandy loam soil or soil with a pH between 6.0 and 7.0 and prepare soil by well draining.\nii. Sow the Tomato seeds between the March, April ,June and July second sowing continue from November for optimal growth conditions.",
    "Germination and Transplatation":"It takes 5-10 days for the seeds to sprout. Ensure irrigation should be done once in 5 days. After irrigation grass should be removed with the help of workers",
    "Ideal Growth Conditions":"Keep the soil temperature in the range of 24-28°C and ensure regular watering without saturating the soil.",
    "Fertilisation":"Apply balanced fertilizer every month based on the fertility level of soil generally ranges from 0.6-0.85 , use pesticides when there are many pests and insects , Use organic fertilisers.",
    "Harvesting":"Harvest usually happens in 120-150 days from sowing. With good irrigation, Tomato plants can significantly yield 10-15 tons per acre. Ensure price based on the demand in market. Once yield is ready start exporting the goods",
  },
  {
    "Name":"Wheat",
    "Category":"Crop Category",
    "Sowing":"i. Prior to sowing, assess if the soil is suitable for wheat cultivation, favoring soil with a pH between 6.0 and 8.0 and prepare soil by well draining.\nii. Sow the wheat seeds between oct 15 and Nov 15 in Northern India, Nov 1 and Dec 15 in central India ,Dec 1 and Jan 15in Southern India  for optimal growth conditions.",
    "Ideal Growth Conditions":"Prepare soil by three methods plowing(20-25 cm deep), Harrowing(10-15 cm deep) and levelling ",
    "Germination and Transplantation":"It takes 7-10 days for the seeds to sprout. Wash away any excess weeds by proper irrigation and fertilisation. ",
    "Fertilisation":"Apply balanced fertilizers every month like Urea, DAP, Patash etc. Use pesticides when there are many  wheat pests like IPM etc, and adjust fertilizer based on soil fertility levels.",
    "Harvesting":"Harvest usually happens in march and april. With good irrigation, wheat plants can yield 4.5-5.5 t/ha Make sure to cut carefully with clean tools and store the harvest in a dry and well ventilated areas",
  },
  {
    "Name":"Red Gram",
    "Category":"Pulses",
    "Sowing" : "i. Prior to sowing, assess if the soil is suitable for Red Gram cultivation, favoring loam soil or soil with a pH between 6.5 and 7.5 and prepare soil by plowing and ferdows and hedges should be prepared.\nii. Seeds are to be treated with trichodema virade or Pseudomonas fluorescence before swoing. \niii. Sow the Red Gram seeds between the June, July and may recommerence by october and november for optimal growth conditions." ,
    "Ideal Growth Conditions":" Keep the soil temperature in the range of 28-34°C and ensure regular watering without saturating the soil" ,
    "Germination and transplantation":" It takes a week approx for the seeds to sprout. Once irrigation was done grass is removed with the help of workers.",
    " Fertilisation":" The approx fertility level is between 0.6-0.85. Balanced Fertilisers such as NPK-10:20:10,FYM:5 should be used. Pesticides are to be used to control pests and insects." ,
    "Harvesting":" Harvest usually happens in 6-8 months from sowing period. With good irrigation, Red Gram crop can yield 800-1000 kgs/acres . Fix the price based on market demand. Once yield is ready start export the goods. " ,
  },
  {
    "Name":"Maize",
    "Category":"Crop Category",
    "Sowing" :" i. Prior to sowing, assess if the soil is suitable for Maize cultivation, favoring sandy loam and aluvium soils or soil with a pH between 5.5 and 7.5 and prepare soil by well draining.\nii. Before sowing seeds are to be treated with carbendazim and thiram.\niii. Sow the Maize seeds between the  June and July second sowing from october ,November ,January and February for optimal growth conditions. " ,
    "Ideal Growth Conditions" : "Keep the soil temperature in the range of 24-29°C and ensure regular watering without saturating the soil. Advisable to maintain wetness to crop for twice a week and ploghing 3 times a week." ,
    "Germination and transplantation": "It takes 4 days for the seeds to sprout. " ,
    "Fertilisation":" Apply balanced fertilizer every month, use pesticides when there are many Maize pests, and adjust fertilizer based on soil fertility levels. Generally fertility levels ranges from 0.6-0.85." ,
    "Harvesting" : "Harvest usually happens in 105-110 days from sowing. With good irrigation, maize plants can yield a significant quantity of 600-8000 kgs\\acre. Ensure price based on the demad in market. Once yield is done start exporting the goods." ,
  },
  {
    "Name":"Cotton",
    "Category":"Commercial",
    "Sowing" : "i. Prior to sowing, assess if the soil is suitable for Cotton cultivation, favoring deep loamy or clay loam soils or soil with a pH between 5.8 and 8.0 and prepare soil by well draining.\nii. Sow the Cotton seeds between the  may and june in irrigated areas, june and july in Rain Fed areas. " ,
    "Ideal Growth Conditions": "Regular weeding, thinning of weak plants and removal of ecxess seedlings should be done " ,
    "Germination and transplantation": "It takes 5-10 days for the seeds to sprout. Generally direct sown but in occassional cases seedlings are transplanted 3-4 weeks after sowing. " ,
    "Fertilisation" : "Apply balanced amount of nitrogen, phosphorus, and potassium based on soil test. For organic type of cotton compost, farmyard manure, and biofertilizers are used. Recommended to use pre emergent herbicides in order to control weeds. " ,
    "Harvesting": " Harvest usually happens when 60-70 % of the balls are open. Generally in the period between october and january.With proper range of irrigaton and care cotton can yield 8-12 quintals/hec. Ensure the price based on the market demand." ,
  },
  {
    "Name":"Sugarcane",
    "Category":" Food",
    "Sowing" : "i. Prior to sowing, assess if the soil is suitable for Sugarcane cultivation, favoring sandy loam and clayloam  soils or soil with a pH between 6.5 and 7.5 and prepare soil by well draining.\nii. Sow the Sugarcane seeds between the  September and October second sowing between February and March for optimal growth conditions. " ,
    "Ideal Growth Conditions" : "Advisible to maintain wetness of the crop for twice a week. Before ploghing clearing of aoil ahould be done. " ,
    "Germination and transplantation":" It takes 12 - 16 days for the seeds to sprout. After germination the sets were cut by shoots and sink for treating with cardendazim mixed in water.Maintain 7.5 to 10 cm of thick sugarcane grass for mulching." ,
    "Fertilisation": "Apply balanced fertilizer every month, use pesticides when there are many sugarcane pests, and adjust fertilizer based on soil fertility levels like NPK- 120:40:80,FYM- 4. Generally fertility levels ranges from 0.6-0.85." ,
    "Harvesting": "Harvest usually happens in 350-370 days from sowing. With good irrigation and proper care  Sugarcane can yield a significant quantity of 60-80 tons\\acre. Ensure price based on the demad in market. Once yield is done start exporting the goods" ,
  },
  {
    "Name":"Green Gram",
    "Category":"Pulses",
    "Sowing" : "i. Prior to sowing, assess if the soil is suitable for Green gram cultivation, favoring sandy loam soil or loam soil with a pH between 6.5 and 7.5 and prepare soil by well draining.\nii. Sow the Tomato seeds between the end of June, July, september and october second sowing continue from january, february and march for optimal growth conditions.\niii.Seeds are to be treated with capton or thiram before sowing " ,
    "Ideal Growth Conditions":"Ensure to irrigate the crop if field is of remain water type or if water is available use rain gun method once a week. After irrigation was done remove all the waste plants like grass." ,
    "Germination and transplantation":"It takes 3-4 days for the seeds to sprout. Prior to transplanting ploughing should be done for clearing and soil smoothening ." ,
    "Fertilisation":"Apply balanced fertilizer like NPK-10:20:10, FYM-4 every month based on the fertility level  of soil generally ranges from 0.7-0.85 , use pesticides when there are many pests and insects , Use organic fertilisers. " ,
    "Harvesting": "Harvest usually happens in 80-100 days from sowing. With good irrigation and care Sugarcane plants can significantly yield 3-5 qntls per acre. Ensure price based on the demand in market. Once yield is ready start exporting the goods. " ,
  },
  {
    "Name":"Bajra",
    "Category":"Pulses",
    "Sowing" : "i. Prior to sowing, assess if the soil is suitable for Bajra cultivation, favoring black and sandy loam soil or soil with a pH between 4.8 and 6.0 and prepare soil by well draining.\nii. Sow the Bajra seeds between june and july for optimal growth conditions.\niii.Seeds are to be treated with Trichoderma harzanium before sowing " ,
    "Ideal Growth Conditions" : "Ensure to maintain wetness of crop twice a week and 3 time ploghing is advisable in order to reduce debris. Remove grass plants with the help pf workers." ,
    "Germination and transplantation": "It takes 2-3 days for the seeds to sprout. Seedlings emerges within a month. " ,
    "Fertilisation" : "Apply balanced fertilizer like NPK-8:8:8, FYM-4 every month based on the fertility level  of soil generally ranges from 0.6-0.85 , use pesticides when there are many pests and insects , Use organic fertilisers. " ,
    "Harvesting" : "Harvest usually happens in 3 months from sowing. With good irrigation and care Bajra plants can significantly yield 1 ton per acre. Ensure price based on the demand in market. Once yield is ready start exporting the goods." ,
  },
  {
    "Name":"Jowar",
    "Category":"Pulses",
    "Sowing ": "i. Prior to sowing, assess if the soil is suitable for Jowar cultivation, favouring aluvial and clay loam soil or soil with a pH between 6.0 and 7.5 and prepare soil by well draining.\nii. Sow the Tomato seeds between October and March for optimal growth conditions.\niii.Seeds are to be treated with sulfur or thiram before sowing." ,
    "Ideal Growth Conditions":"Ensure to maintain wetness twice a week. advisible to plough 3 times a week in order to remove debris." ,
    "Germination and transplantation": "It takes 2-3 days for the seeds to sprout. Seedlings emerges in a month. Grass plants should be removed with the help of workers." ,
    "Fertilisation" : "Apply balanced fertilizer like NPK-24:16:16, FYM-4 every month based on the fertility level  of soil generally ranges from 0.7-0.85 , use pesticides when there are many pests and insects , Use organic fertilisers." ,
    "Harvesting" : "Harvest usually happens in 80-100 days from sowing. With good irrigation and care Jowar plants can significantly yield 12 qntls per acre. Ensure price based on the demand in market. Once yield is ready start exporting the goods" ,
  }
];