name: demo_mvp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  http: ^1.2.2
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1
  flutter_dotenv: ^5.1.0
  provider: ^6.1.2
  razorpay_flutter: ^1.3.7
  speech_to_text: ^6.6.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  image_picker: ^1.1.2
  firebase_storage: ^12.2.0
  translator: ^1.0.0
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  image_path_android: 'assets/krishi_sahayak.png'
  android: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - .env
